# path to seed hap 1 & 2
# consider using bwa index and samtools faidx to index the files
#https://www.biostars.org/p/12417/
genomes:
  SEED_HAP_1: DATA/TaeGut/bTaeGut1.pri.final.fasta
  SEED_HAP_2: DATA/TaeGut/mutated.final.fasta
  contam1: DATA/ecoli/ecoli.fasta
  contam2: DATA/human/humanmat.fasta

# set up a different amount of cores for jobs that should run fewer than the rest of the analysis
CORES: 50

#busco db to use
LINEAGE: aves_odb10

sample_prefix: TaeGut

chrom_num: 41

read_length: 3500

depth: 0.75
